// Objective-C API for talking to neuralNetwork Go package.
//   gobind -lang=objc neuralNetwork
//
// File is generated by gobind. Do not edit.

#ifndef __NeuralNetwork_H__
#define __NeuralNetwork_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class NeuralNetworkInputParamNetwork;
@class NeuralNetworkInputPredictParam;
@class NeuralNetworkNeuralNetConfig;
@class NeuralNetworkResultNetWork;
@class NeuralNetworkResultPredict;

/**
 * InputParamNetwork param input for network
 */
@interface NeuralNetworkInputParamNetwork : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NeuralNetworkNeuralNetConfig* _Nullable config;
@property (nonatomic) long countRow;
// skipped field InputParamNetwork.InputData with unsupported type: []float64

// skipped field InputParamNetwork.OutputData with unsupported type: []float64

@property (nonatomic) long countRowTest;
// skipped field InputParamNetwork.TestData with unsupported type: []float64

// skipped field InputParamNetwork.LabelData with unsupported type: []float64

@end

/**
 * InputPredictParam param use for predict data
 */
@interface NeuralNetworkInputPredictParam : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NeuralNetworkNeuralNetConfig* _Nullable config;
@property (nonatomic) NeuralNetworkResultNetWork* _Nullable networkModel;
@property (nonatomic) long numberRow;
// skipped field InputPredictParam.InputData with unsupported type: []float64

@end

/**
 * NeuralNetConfig object
 */
@interface NeuralNetworkNeuralNetConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long inputNeurons;
@property (nonatomic) long outputNeurons;
@property (nonatomic) long hiddenNeurons;
@property (nonatomic) long numEpochs;
@property (nonatomic) double learningRate;
@end

/**
 * ResultNetWork save result of network
 */
@interface NeuralNetworkResultNetWork : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field ResultNetWork.WHidden with unsupported type: []float64

// skipped field ResultNetWork.BHidden with unsupported type: []float64

// skipped field ResultNetWork.WOut with unsupported type: []float64

// skipped field ResultNetWork.BOut with unsupported type: []float64

@property (nonatomic) double correlationValue;
@end

@interface NeuralNetworkResultPredict : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long numberRow;
@property (nonatomic) long numberOutPut;
// skipped field ResultPredict.OutData with unsupported type: []float64

@end

/**
 * PredictNeuralWithJSON demo predict value
 */
FOUNDATION_EXPORT NSString* _Nonnull NeuralNetworkPredictNeuralWithJSON(NSString* _Nullable modelNetwork, NSString* _Nullable configValue, NSString* _Nullable inputData);

// skipped function PredictWithNeural with unsupported parameter or return types


/**
 * ProcessNeuralWithJSON with json value
 */
FOUNDATION_EXPORT NSString* _Nonnull NeuralNetworkProcessNeuralWithJSON(NSString* _Nullable configValue, NSString* _Nullable value);

#endif
