
// Objective-C API for talking to the following Go packages
//
//	neuralNetwork
//
// File is generated by gomobile bind. Do not edit.
#ifndef __NeuralNetwork_FRAMEWORK_H__
#define __NeuralNetwork_FRAMEWORK_H__

#include "NeuralNetwork.objc.h"
#include "Universe.objc.h"

#endif
