
// Objective-C API for talking to the following Go packages
//
//	github.com/TriTranDev/neuralnetworkmobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Neuralnetworkmobile_FRAMEWORK_H__
#define __Neuralnetworkmobile_FRAMEWORK_H__

#include "Neuralnetworkmobile.objc.h"
#include "Universe.objc.h"

#endif
